Added Documentation for Syncthing
liaralabs/docs.swizzin.ltd pull request #55
Opened 2021-03-21 04:59 UTC by HarleyL7

Added docs for Syncthing. 
1. SSH command to install
2. configure by setting up remote devices and sharing folders.

2021-03-21 05:09 UTC, brettpetch commented
Looks generally fine. @flying-sausages will likely have a boo when he has a minute to provide you some feedback :)

2021-03-21 10:58 UTC, flying-sausages requested changes
Just needs a bittle more here and there

2021-03-22 08:43 UTC, flying-sausages approved these changes

2021-03-22 08:43 UTC, flying-sausages commented
Thanks for the supports!

2021-03-22 08:43 UTC, merged