Requestrr Docs
liaralabs/docs.swizzin.ltd pull request #56
Opened 2021-03-22 04:30 UTC by HarleyL7

Added docs for requestrr

2021-03-22 04:44 UTC, brettpetch requested changes

2021-03-22 04:44 UTC, brettpetch commented on docs/applications/requestrr.mdx
> +
you need to close tabs. see this for an example: 
https://pipelines.actions.githubusercontent.com/etBdarlm6eMDwSa1NkNZo2fsgjLVPIg6bOIIEVHCrEhB8zbABn/_apis/pipelines/1/runs/153/signedlogcontent/4?urlExpires=2021-03-22T04%3A33%3A59.4675604Z&urlSigningMethod=HMACV1&urlSignature=5qZUA7K5FB0aFQlBVY7aw6IzQhf3cr%2F8ZeTGcCdTCqw%3D

2021-03-22 04:44 UTC, brettpetch commented on docs/applications/requestrr.mdx
> +<TabItem value="radarr">
should be indented, as is a tag under tabs. others too.

2021-07-15 19:54 UTC, brettpetch commented
@HarleyL7 you may need to modify your branch a bit... you forgot to add docs for the application to the sidebar.

/b

2021-07-15 20:50 UTC, flying-sausages commented
++ the frontpage list of applications

2022-01-15 23:00 UTC, closed without merging